**Question-1:** Create a function to check whether numpy array has Zero values or not.

In [9]:
import numpy as nump

new_array_1 = nump.array([2 , 5 , 8 , 9 , 12])
new_array_2 = nump.array([2 , 5 , 8 , 9 , 12 , 50 , 0 , 13])

# Here to check whether an numpy array contains the zero we will use numpy.all() method....

print(nump.all(new_array_1))
print(nump.all(new_array_2))

True
False


**Question-2:** Consider an array contains marks of students. Find the median and mean of students who got passing marks.

In [4]:
import numpy as nump

def mean_calculation(arr , length):
  sum=0
  for i in range(0 , length):
    sum+= arr[i]
    
  mean = float (sum/length)
  print(mean)

def median_calculation(arr, length):
  sorted(arr)
  median = 0
  if length % 2 != 0:
    median = float(arr[int (length / 2)]) 
  else: 
    median = float(arr[int((length-1)/2)] + arr[int(length/2)]) /2
    
  print(median)


# Creating an numpy array
new_array = nump.array([1 , 2 , 3 , 4 , 5, 6])
length = len(new_array)
print("Mean = ", end = " ")
mean_calculation(new_array , length)
print("Median = ", end = " ")
median_calculation(new_array, length)

# Another method in order to find out the mean and median for numpy array which is
# by using mean() and median() methods available under numpy....

print("Mean and Median using numpy methods are......")
print ("Mean =", end = " ")
print(float(nump.mean(new_array)))

print("Median =", end = " ")
print(float(nump.median(new_array)))


Mean =  3.5
Median =  3.5
Mean and Median using numpy methods are......
Mean = 3.5
Median = 3.5


**Question-3:** Consider an array containing date of birth of students (Use np.datetime64('2018-02-01')). Find the age of all students. If age is 18 label it First, if it is 19, label it Second, if it is 20, label it Third, if it is 21, label it Fourth.

In [23]:
import numpy as nump

# Creating students date of birth array....
students_dob_array = nump.array([nump.datetime64('2004-02-01') , nump.datetime64('2003-03-01'), nump.datetime64('2004-02-01'), nump.datetime64('2002-02-01'), nump.datetime64('2001-03-01') ])
print('Students DOB Arrays.....')
print(students_dob_array)

# Calculating years from students date of births array....
students_years = students_dob_array.astype('datetime64[Y]').astype(int) + 1970

# Calculating ages of all the students...
current_year = 2022
student_ages_array = []
for student_year in students_years:
  student_ages_array.append(current_year - student_year)

# Printing age along with labelling.......

for age in student_ages_array:
  if age == 18:
    print("First : ", age)
  elif age == 19:
    print("Second : ", age)
  elif age == 20:
    print("Third : ", age)
  elif age == 21:
    print("Fourth : ", age)  



Students DOB Arrays.....
['2004-02-01' '2003-03-01' '2004-02-01' '2002-02-01' '2001-03-01']
First :  18
Second :  19
First :  18
Third :  20
Fourth :  21


**Question-4:** Create a function to sort 2d Array by a column.

In [8]:
import numpy as nump

# Creating a 2d array..

numpy_2d_array = nump.array([ [10 , 6 , 5 , 4] , [55 , 78 , 20 , 40] , [13 , 14 , 21 , 16] ])
print("Numpy 2d Array.....")
print(numpy_2d_array)

# Sorting a 2d array using an index value....

column_index = 0
column_sorted_array = numpy_2d_array[numpy_2d_array[:, column_index].argsort()]
print("Sorted Array based on column index.....")
print(column_sorted_array)

Numpy 2d Array.....
[[10  6  5  4]
 [55 78 20 40]
 [13 14 21 16]]
Sorted Array based on column index.....
[[10  6  5  4]
 [13 14 21 16]
 [55 78 20 40]]
